# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 643dcce71c6a9e0c824125d1edeb970e17dc5c3de2c9a64f18ba93abf504a8f36bc454389c13bf4bffe6db095df9ac67bf38342e376a9cc0fc5368cbf476dc75

test:
  secret_key_base: d8c407c78caea819f8454a2869bc1e527db00a19ca8b7e3f45363c10e3edc08ea9207083578f1360fc91bc5d2493625a15b73c8fa27da71c195b3e3d7974179a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
